







	



.build/leonardo/Adafruit_NeoPixel/Adafruit_NeoPixel.d : lib/Adafruit_NeoPixel/Adafruit_NeoPixel.cpp
	@mkdir -p .build/leonardo/Adafruit_NeoPixel
	@/usr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/MicroView -Ilib/MicroView/MicroView-Arduino-Library -Ilib/Adafruit_NeoPixel -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/SPI  -MM $^ > $@
	
	@printf ".build/leonardo/Adafruit_NeoPixel/Adafruit_NeoPixel.d .build/leonardo/Adafruit_NeoPixel/" | cat - $@ > $@~ && mv $@~ $@



.build/leonardo/Adafruit_NeoPixel/dependencies.d : .build/leonardo/Adafruit_NeoPixel/Adafruit_NeoPixel.d
	@echo [96mScanning dependencies of Adafruit_NeoPixel[0m
	@mkdir -p .build/leonardo/Adafruit_NeoPixel
	@cat $^ > $@;

all : .build/leonardo/Adafruit_NeoPixel/dependencies.d
	@true

