







	



.build/uno/CapacitiveSensor/CapacitiveSensor.d : lib/CapacitiveSensor/CapacitiveSensor.cpp
	@mkdir -p .build/uno/CapacitiveSensor
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/CapacitiveSensor -Ilib/MicroView -Ilib/MicroView/MicroView-Arduino-Library -Ilib/Adafruit_NeoPixel -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/SPI  -MM $^ > $@
	
	@printf ".build/uno/CapacitiveSensor/CapacitiveSensor.d .build/uno/CapacitiveSensor/" | cat - $@ > $@~ && mv $@~ $@



.build/uno/CapacitiveSensor/dependencies.d : .build/uno/CapacitiveSensor/CapacitiveSensor.d
	@echo [96mScanning dependencies of CapacitiveSensor[0m
	@mkdir -p .build/uno/CapacitiveSensor
	@cat $^ > $@;

all : .build/uno/CapacitiveSensor/dependencies.d
	@true

