#!/bin/bash

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install nodejs npm unclutter dnsmasq ca-certificates hostapd
sudo aptitude install network-manager-kde network-manager
git clone https://imajon@bitbucket.org/imajon/noob.git
#cd noob/
#sudo npm install socket.io twit instagram-node
#cd
#git clone git://git.drogon.net/wiringPi
cd noob/wiringPi/
./build
sudo wget -O /lib/firmware/isl3887usb https://daemonizer.de/prism54/prism54-fw/fw-usb/2.13.25.0.lm87.arm
modprobe -r p54usb ; modprobe p54usb
#tar -xvvf pyserial-2-1.5.tar
#cd pyserial-2.5/
#sudo python setup.py install
echo 'Etape 1 OK'

cd
sudo rm -rf wiringpi
sudo mv /home/pi/noob/scripts/startNodejs /etc/init.d/
sudo update-rc.d startNodejs defaults

sudo mv /home/pi/noob/scripts/autostart /etc/xdg/lxsession/LXDE
#sudo mv /home/pi/noob/scripts/startRFID /etc/init.d/
#sudo update-rc.d startRFID defaults

sudo mv /home/pi/noob/scripts/showIP /etc/init.d/
sudo update-rc.d showIP defaults

sudo mv /home/pi/noob/scripts/pythonMirror.py /home/pi/
sudo mv /home/pi/noob/scripts/mirror.rules /etc/udev/rules.d/mirror.rules
sudo /etc/init.d/udev restart

sudo mv /home/pi/noob/PCD /home/pi/
sudo mv /home/pi/noob/scripts/blink_l.sh /home/pi/blink-s.sh
sudo mv /home/pi/noob/scripts/interfaces /etc/network
sudo mv /home/pi/noob/scripts/hostapd/hostapd.conf /etc/hostapd/hostapd.conf 
sudo mv /home/pi/noob/scripts/wpa_supplicant.conf /etc/wpa_supplicant/

echo 'Etape 2 OK'

