#! /bin/sh
# /etc/init.d/startNodejs

### BEGIN INIT INFO
# Provides:          Nodejs
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script which will start / stop a program a boot /$
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Demarrage de Nodejs chat"
        cd /home/pi/noob
	nodejs server_chat.js > /home/pi/result_server_chat
        ;;
    stop)
        echo -n "Arret de Nodejs chat  non requis."
        ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0

