#! /bin/sh
# /etc/init.d/startRFID 

### BEGIN INIT INFO
# Provides:          RFID
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script which will start / stop a program a boot /$
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Demarrage de server.py"
        sudo python /home/pi/pythonMirror.py &
        ;;
    stop)
        echo -n "Arret de server.py non requis."
        ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
